apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-order-service
  template:
    metadata:
      labels:
        app: cart-order-service
    spec:
      containers:
        - name: cart-order-service
          image: briandoan/cart-order-service:1.0.0
          ports:
            - containerPort: 4004
          env:
            - name: POSTGRESQL_URL
              value: jdbc:postgresql://postgres:5432/microsimu-cartorder
            - name: POSTGRESQL_USERNAME
              value: postgres
            - name: POSTGRESQL_PWD
              value: postgres
            - name: REDIS_URL
              value: redis://redis:6379
            - name: KAFKA_BROKERS
              value: kafka1:29092,kafka2:29092,kafka3:29092
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cart-order-service
spec:
  selector:
    app: cart-order-service
  ports:
    - port: 4004
      targetPort: 4004
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-order-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-order-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80