apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-gateway-service
  template:
    metadata:
      labels:
        app: external-gateway-service
    spec:
      containers:
        - name: external-gateway-service
          image: briandoan/external-gateway-service:1.0.0
          ports:
            - containerPort: 4001
          env:
            - name: KAFKA_BROKERS
              value: kafka1:29092,kafka2:29092,kafka3:29092
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: external-gateway-service
spec:
  selector:
    app: external-gateway-service
  ports:
    - port: 80
      targetPort: 4001
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: external-gateway-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-gateway-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80